[package]
name = "rpki-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
rmcp = { version = "0.11.0", features = ["transport-io"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
